"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.META_ROUTER = Symbol.for('dectorator#meta_router');
exports.META_CONTROLLER = Symbol.for('dectorator#meta_controller');
exports.META_INJECT = Symbol.for('dectorator#meta_inject');
exports.META_REQ = Symbol.for('decorator#meta_req');
exports.META_RES = Symbol.for('decorator#meta_res');
exports.META_HEADERS = Symbol.for('decorator#meta_headers');
exports.META_PARAMS = Symbol.for('decorator#meta_params');
exports.META_BODY = Symbol.for('decorator#meta_body');
exports.META_COOKIE = Symbol.for('decorator#meta_cookie');
exports.META_PASSPORT = Symbol.for('decorator#meta_passport');
exports.META_RPC_CLIENT = Symbol.for('decorator#meta_rpc_client');
exports.META_RPC_SERVER = Symbol.for('decorator#meta_rpc_server');
